name: dotlin_generator
description: Generates ProtoBuf Dart elements for use in the Dotlin compiler.
version: 0.0.2
homepage: https://dotlin.org
repository: https://github.com/dotlin-org/dotlin

environment:
  sdk: '>=2.18.2 <3.0.0'

executables:
  generate: generate

dependencies:
  analyzer: ^5.2.0
  path: ^1.8.2
  package_config: ^2.1.0
  dartx: ^1.1.0
  protobuf: ^2.1.0
  fixnum: ^1.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.0
  protoc_builder: ^0.3.0
